name: Unified Labeler

on:
  label:
    types: [created, deleted, edited]

jobs:
  unified-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20

      - name: Unified Labeler
        uses: jill64/unified-labeler@main
        with:
          name: ${{ github.event.label.name}}
          action: ${{ github.event.action }}
